#!/bin/bash

# Create directory
mkdir -p public/stockfish

echo "Downloading Stockfish.js (v10) from cdnjs..."

# CDNs for Stockfish.js
# We use version 10.0.0 as it's stable and widely available on cdnjs
BASE_URL="https://cdnjs.cloudflare.com/ajax/libs/stockfish.js/10.0.0"

# Download stockfish.js
curl -L "$BASE_URL/stockfish.js" -o public/stockfish/stockfish.js
if [ $? -eq 0 ]; then
    echo "✅ stockfish.js downloaded"
else
    echo "❌ Failed to download stockfish.js"
fi

# Download stockfish.wasm
curl -L "$BASE_URL/stockfish.wasm" -o public/stockfish/stockfish.wasm
if [ $? -eq 0 ]; then
    echo "✅ stockfish.wasm downloaded"
else
    echo "❌ Failed to download stockfish.wasm"
fi

# Note: stockfish.worker.js is not needed for this version/build interaction pattern 
# or is generated by the main script for some builds.
# We'll just ensure clean state
rm -f public/stockfish/stockfish.worker.js

echo "Stockfish installation complete (v10)."
echo "For newer versions (Stockfish 16+ NNUE), download manually from https://stockfishchess.org/download/"
